mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import logout_view, MyLogoutView, set_cookie_view, get_cookie_view, set_session_view, get_session_view, \
    AboutMeView, RegisterView, FooBarView, AvatarUpdateView, ProfileCreateView, UserListView, UserDetailView, HelloView

app_name = 'myauth'
urlpatterns = [
    # path('login/', login_view, name='login'),
    path('login/',
         LoginView.as_view(
             template_name='myauth/login.html',
             redirect_authenticated_user=True,
         ),
         name='login'),

    path('hello/', HelloView.as_view(), name='hello'),
    path('logout/', logout_view, name='logout'),

    path('about-me/', AboutMeView.as_view(), name='about_me'),
    path('register/', RegisterView.as_view(), name='register'),

    path('cookie/get', get_cookie_view, name='cookie_get'),
    path('cookie/set', set_cookie_view, name='cookie_set'),

    path('session/get', get_session_view, name='session_get'),
    path('session/set', set_session_view, name='session_set'),


    path('foo-bar/', FooBarView.as_view(), name='foo-bar'),
    path('user-list/', UserListView.as_view(), name='user-list'),
    path("user-details/<int:pk>", UserDetailView.as_view(), name="user-details"),
    path("user-details/<int:pk>/update-profile/", ProfileCreateView.as_view(), name="create-profile"),

    path("user-details/<int:pk>/avatar/", AvatarUpdateView.as_view(), name="change-avatar"),


]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from django.contrib.sitemaps.views import sitemap

from .sitemaps import sitemaps


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api/schema/swager/', SpectacularSwaggerView.as_view(url_name='schema'), name='swager'),
    path('api/', include('myapiapp.urls')),
    path('blog/', include('blogapp.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
]

urlpatterns += i18n_patterns(
    path('accounts/', include('myauth.urls')),
    path('shop/', include('shopapp.urls')),
    path('req/', include('requestdataapp.urls')),
    path('admin/', admin.site.urls),
)

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

mysite/shopapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (ShopIndexView, ProductListView, OrderListView, OrderCreateView, GroupsListView, OrderDeleteView,
                    ProductDetailView, OrderDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView,
                    OrderUpdateView, ProductsDataExportView, OrdersDataExportView,ProductViewSet,OrderViewSet,LatestProductsFeed,
                    UserOrdersListView, UserOrdersDataExportView)
from django.views.decorators.cache import cache_page
app_name = 'shopapp'

router = DefaultRouter()
router.register("products", ProductViewSet)
router.register("orders", OrderViewSet)



urlpatterns = [
    # path("", cache_page(60*3)(ShopIndexView.as_view()), name="shop_index"),
    path("", ShopIndexView.as_view(), name="shop_index"),
    path("api/", include(router.urls)),
    path("groups/", GroupsListView.as_view(), name="groups_list"),
    path("products/", ProductListView.as_view(), name="products_list"),
    path("products/create_product/", ProductCreateView.as_view(), name="create_product"),
    path("products/<int:pk>/", ProductDetailView.as_view(), name="product_details"),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/archive/", ProductDeleteView.as_view(), name="product_archive"),
    path("products/export/", ProductsDataExportView.as_view(), name="products-export"),

    path("orders/", OrderListView.as_view(), name="orders_list"),
    path("orders/create_order/", OrderCreateView.as_view(), name="create_order"),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name="order_details"),
    path("orders/<int:pk>/update/", OrderUpdateView.as_view(), name="order_update"),
    path("orders/<int:pk>/delete/", OrderDeleteView.as_view(), name="order_delete"),
    path("orders/export/", OrdersDataExportView.as_view(), name="orders-export"),
    path("users/<int:user_id>/orders/", UserOrdersListView.as_view(), name="user-orders"),
    path("users/<int:user_id>/orders/export/", UserOrdersDataExportView.as_view(), name="user-orders-export"),

    path("products/latest/feed/", LatestProductsFeed(), name="latest-products"),
]

mysite/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

def product_preview_directory_path(instance: "Product", filename: str) -> str:
    return f"products/product_{instance.pk}/preview/{filename}"

class Product(models.Model):
    """
    Модель Product представляет товар,
    который можно купить в магазине

    Заказы тут: :model:`shopapp.Order`
    """
    class Meta:
        ordering = ['name', 'price']
        # db_table = 'product'
        verbose_name_plural =  _('Products')
        verbose_name = _('Product')

    name = models.CharField(max_length=100, db_index=True)
    description = models.TextField(null=False, blank=True, db_index=True)
    price = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    discount = models.PositiveSmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT)
    preview = models.ImageField(upload_to=product_preview_directory_path, null=True, blank=True)

    # @property
    # def description_short(self)->str:
    #     if len(self.description) < 50:
    #         return self.description
    #     else:
    #         return self.description[:50] + '...'

    def get_absolute_url(self):
        return reverse('shopapp:product_details', kwargs={'pk': self.pk})

    def __str__(self) ->str:
        return f"Product(pk={self.pk}, name={self.name})"


def product_image_directory_path(instance: "Product", filename: str) -> str:
    return f"products/product_{instance.pk}/images/{filename}"

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=product_image_directory_path)
    description = models.CharField(max_length=200, null=False, blank=True)

class Order(models.Model):
    class Meta:
        verbose_name_plural = _('Orders')
        verbose_name = _('Order')

    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT, related_name='orders')
    products = models.ManyToManyField(Product, related_name='orders')
    receipt = models.FileField(null=True, upload_to="orders/receipts")

    def get_absolute_url(self):
        return reverse('shopapp:order_details', kwargs={'pk': self.pk})

mysite/shopapp/views.py
"""
В этом модуле лежат различные наборы представления по заказам и т.д.

Разные view интернет магазина
"""

import logging
from csv import DictWriter
from dataclasses import field

from django.contrib.gis.feeds import Feed
from rest_framework.generics import ListCreateAPIView
from rest_framework.response import Response

from .command import save_csv_products
from rest_framework.parsers import MultiPartParser
from django.contrib.auth.models import Group, User
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, reverse, get_object_or_404
from timeit import default_timer
from datetime import datetime
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views.generic import  ListView, DetailView, CreateView, UpdateView, DeleteView
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.viewsets import ModelViewSet
from rest_framework.filters import SearchFilter
from rest_framework.decorators import action
from rest_framework.request import Request
from .models import Product, Order, ProductImage
from .forms import ProductForm,  GroupForm
from django.views import View
from .serializers import ProductSerializer, OrderSerializer
from drf_spectacular.utils import extend_schema, OpenApiResponse
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator
from django.core.cache import cache

log = logging.getLogger(__name__)


@extend_schema(description="Product View CRUD")
class ProductViewSet(ModelViewSet):
    """
    Набор представлений для действий над Product
    Полный CRUD для сущностей товара
    """
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = (SearchFilter,DjangoFilterBackend)
    search_fields = ('name','description')
    filterset_fields = ['name',
                        'description',
                        'price',
                        'discount',
                        'archived',
                        ]
    ordering_fields = ['name',
                        'price',
                        'discount',
                        ]

    @method_decorator(cache_page(60*2))
    def list(self, *args, **kwargs):
        return super().list(*args, **kwargs)

    @action(detail=False, methods=['GET'])
    def download_csv(self, request: Request):
        response = HttpResponse(content_type='text/csv')
        filename = 'products'
        response['Content-Disposition'] = f'attachment; filename={filename}-export.csv'
        queryset = self.filter_queryset(self.get_queryset())
        fields = ['name',
                'description',
                'price',
                'discount',
                ]
        queryset = queryset.only(*fields)
        writer = DictWriter(response, fieldnames=fields)
        writer.writeheader()
        for product in queryset:
            writer.writerow(
                {
                    field: getattr(product, field)
                    for field in fields
                }
            )
        return response

    @action(detail=False, methods=['post'], parser_classes=[MultiPartParser])
    def upload_csv(self, request: Request):
        products = save_csv_products(
            request.FILES['file'].file,
            encoding=request.encofing
        )
        serializer = self.get_serializer(products, many=True)
        return Response(serializer.data)
    @extend_schema(
        summary='Get one product by ID',
        description='Returns one product by ID',
        responses={
            200: ProductSerializer,
            404: OpenApiResponse(description="Not found"),
        }
    )
    def retrieve(self, *args, **kwargs):
        return super().retrieve( *args, **kwargs)

class OrderViewSet(ModelViewSet):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer
    filter_backends = (SearchFilter,DjangoFilterBackend)
    search_fields = ('name','description')
    filterset_fields = ["delivery_address",
                        "promocode",
                        "created_at",
                        "user",
                        "products",
                        ]
    ordering_fields = ['delivery_address',
                        'user',
                        'products',
                        ]

class ShopIndexView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        products = [
            ('Laptop', 1999),
            ('Desktop', 2999),
            ('Smartphone', 999),
        ]

        context = {
            "time_running": default_timer(),
            "products": products,
            "Now": datetime.now(),
            "items": 5,
        }
        log.debug("Products for shop index: %s", products)
        log.info("Rendering shop index")
        print(context)
        return render(request, 'shopapp/shop-index.html', context=context)


class GroupsListView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        context = {
            "form": GroupForm(),
            "groups": Group.objects.prefetch_related('permissions').all(),
        }
        return render(request, 'shopapp/groups-list.html', context=context)
    def post(self, request: HttpRequest) -> HttpResponse:
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(request.path)


class ProductDetailView(DetailView):
    template_name = 'shopapp/product-details.html'
    # model = Product
    queryset = Product.objects.prefetch_related('images')
    context_object_name = 'product'

class ProductListView(ListView):
    template_name = 'shopapp/products_list.html'
    queryset = Product.objects.filter(archived=False)
    context_object_name = 'products'


class ProductCreateView(PermissionRequiredMixin, CreateView):
    permission_required = "shopapp.add_product"
    model = Product
    fields = "name", "price", 'description', 'discount', 'preview'
    success_url = reverse_lazy("shopapp:products_list")

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

class ProductUpdateView(UserPassesTestMixin, UpdateView):
    def test_func(self):
        if self.request.user.is_superuser:
            return True
        self.object = self.get_object()
        has_edit_perm = self.request.user.has_perm("shopapp.change_product")
        created_by_current_user = self.object.created_by == self.request.user
        return has_edit_perm and created_by_current_user
    model = Product
    # fields = "name", "price", 'description', 'discount', 'preview'
    form_class = ProductForm
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse(
            "shopapp:product_details",
            kwargs={"pk": self.object.pk}
        )

    def form_valid(self, form):
        response = super().form_valid(form)
        for image in form.files.getlist("images"):
            ProductImage.objects.create(
                product=self.object,
                image=image,
            )
        return response


class ProductDeleteView(DeleteView):
    model = Product
    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class OrderListView(LoginRequiredMixin, ListView):
    queryset = (Order.objects
                .select_related("user")
                .prefetch_related("products")
                )


class OrderDetailView(PermissionRequiredMixin, DetailView):
    permission_required = "shopapp.view_order"
    queryset = (Order.objects
                .select_related("user")
                .prefetch_related("products")
                )

class OrderCreateView(CreateView):
    model = Order
    fields = "delivery_address", "promocode", "user", "products"
    success_url = reverse_lazy("shopapp:orders_list")

class OrderUpdateView(UpdateView):
    model = Order
    fields = "delivery_address", "promocode", "user", "products"
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse(
            "shopapp:order_details",
            kwargs={"pk": self.object.pk}
        )


class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy("shopapp:orders_list")


class ProductsDataExportView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        products = Product.objects.order_by("pk").all()
        products_data = [
            {
                "pk": product.pk,
                "name": product.name,
                "price": product.price,
                "archived": product.archived,
            }
            for product in products
        ]
        elem = products_data[0]
        # name = elem["naem"]
        # print(name)
        return JsonResponse({"products": products_data})

class OrdersDataExportView(UserPassesTestMixin, View):
    def test_func(self):
        if self.request.user.is_staff:
            return True
    def get(self, request: HttpRequest) -> JsonResponse:
        orders = Order.objects.order_by("pk").all()
        orders_data = [
            {
                "pk": order.pk,
                "delivery_address": order.delivery_address,
                "promocode": order.promocode,
                "user_id": order.user.pk,
                "product_list": [p.pk for p in order.products.all()],
            }
            for order in orders
        ]
        return JsonResponse({"orders": orders_data})


class LatestProductsFeed(Feed):
    title = "Products list (latest)"
    description = "Updates or change products"
    link = reverse_lazy("shopapp:products_list")
    def items(self):
        return (

mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base Title
        {% endblock %}
    </title>
</head>
<body>
{% block body %}
    Base body
{% endblock %}
<div>
    {% now 'H:i' %}
</div>
<div>
    {% now 'l' as current_weekday %}
    Today is {{ current_weekday }}
</div>
</body>
</html>

mysite/shopapp/templates/shopapp/create_product.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>Create new product</h1>
    <div>
     <form method="post">
         {% csrf_token %}

         {{ form.as_p }}

         <button type="submit">Submit</button>
     </form>
    </div>

    <div>
        <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Groups List
{% endblock %}

{% block body %}
  <h1>Groups:</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
  <div>
  {% if not groups %}
    <h3>No groups yet</h3>
  {% else %}
    <ul>

      {% for group in groups %}
          <li>
            <div>{{ group.name }}</div>
            <ul>
              {% for permission in group.permissions.all %}
                <li>
                  {{ permission.name }}
                  (<code>{{ permission.codename }}</code>)
                </li>
              {% endfor %}

            </ul>
          </li>
      {% endfor %}

    </ul>
  {% endif %}
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Delete order
{% endblock %}

{% block body %}
    <h1>Are you sure want to Delete {{ object.name }}?</h1>
    <br>
    <div>
        <a href="{% url 'shopapp:order_details' pk=object.pk %}">Back to order</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Delete</button>
        </form>

    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Orders list
{% endblock %}

{% block body %}
    <h1> Orders: </h1>
    {% if object_list %}
        {% for order in object_list %}
            <div>
            <p><a href="{% url 'shopapp:order_details' pk=order.pk %}"> Deteils#{{ order.pk }}</a> </p>
        	<p>Order by: {% firstof order.user.first_name order.user.username %}</p>
        	<p>Promocode: {{ order.promocode }}</p>
        	<p>Delivery address: {{order.delivery_address}}</p>
            <div>
                Products in order:
                <ul>
                    {% for product in order.products.all %}
                        <li>{{ product.name }} for ${{ product.price }}</li>
                    {% endfor %}

                </ul>
            </div>
        	</div>
        {% endfor %}
        
    {% else %}
        <h3> No Orders yet</h3>
    {% endif %}

    <div>
        <a href="{% url 'shopapp:create_order' %}">Create new order</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Update product
{% endblock %}

{% block body %}
    <h1>Update order</h1>
    <div>
     <form method="post">
         {% csrf_token %}

         {{ form.as_p }}

         <button type="submit">Submit</button>
     </form>
    </div>

    <div>
        <a href="{% url 'shopapp:order_details' pk=object.pk %}">Back to order #{{ object.pk }}</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/orders_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
    {% load admin_urls %}
	<li>
    <a href="{% url 'admin:import_orders_csv' %}" class="addlink">
        Import CSV
    </a>
    </li>
    {{ block.super }}
{% endblock %}

mysite/shopapp/templates/shopapp/product-details.html
{% extends 'shopapp/base.html' %}
{% load i18n %}

{% block title %}
  {% translate 'Product' %} #{{ product.pk }}
{% endblock %}

{% block body %}
    <h1>{% translate 'Product' %} <strong>{{ product.name }}</strong></h1>
    <div>
        <div>{% translate 'Description' %}: <em>{{ product.description }}</em></div>
        <div>{% translate 'Price' %}: {{ product.price }}</div>
        <div>{% translate 'Discount' %}: {{ product.discount }}</div>
        <div>{% translate 'Archived' %}: {{ product.archived }}</div>
        {% if product.preview %}
            <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">            
        {% endif %}
        <h3>{% translate 'Images' %}</h3>
        <div>
            <div>
            {% blocktranslate count image_count=product.images.all|length %}
                There is only one images.
                {% plural %}
                There are {{ image_count }} images.
            {% endblocktranslate %}
            </div>
            {% for image in product.images.all %}
                <div>
                    <img src="{{ image.image.url }}" alt="{{ image.image.name }}">
                </div>
            	<div>{{ image.description }}</div>
            {% endfor %}
            
            
        </div>
    
    
    
    </div>
    {% url 'shopapp:product_archive' pk=product.pk as product_archive_url%}
    {% url 'shopapp:product_update' pk=product.pk as product_update_url %}
    {% url 'shopapp:products_list' as products_list_url%}
    {% blocktranslate %}
    <div>
        <a href="{{ product_archive_url }}">Update product</a>
    </div>
    <div>
        <a href="{{ product_update_url }}">Archive product</a>
    </div>
    <div>
        <a href="{{ products_list_url }}">Back to product</a>
    </div>
    {% endblocktranslate %}
{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Archive product
{% endblock %}

{% block body %}
    <h1>Are you sure want to archive {{ object.name }}?</h1>
    <br>
    <div>
        <a href="{% url 'shopapp:product_details' pk=object.pk %}">Back to product</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Archive</button>
        </form>

    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>Create new product</h1>
    <div>
     <form method="post" enctype="multipart/form-data">
         {% csrf_token %}

         {{ form.as_p }}

         <button type="submit">Submit</button>
     </form>
    </div>

    <div>
        <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
    {% load admin_urls %}
	<li>
    <a href="{% url 'admin:import_products_csv' %}" class="addlink">
        Import CSV
    </a>
    </li>
    {{ block.super }}
{% endblock %}

mysite/shopapp/templates/shopapp/products_list.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
    {% translate 'Products list' %}
{% endblock %}

{% block body %}
    <h1> {% translate 'Products' %}: </h1>
    {% if products %}
        <div>
            {% blocktranslate count product_count=products|length %}
                There is only one product.
                {% plural %}
                There are {{ product_count }} product.
            {% endblocktranslate %}
        </div>
        {% for product in products %}
            <div>
                <p><a href="{% url 'shopapp:product_details'  pk=product.pk %}" >{% translate 'Name' context 'product name' %}: {{ product.name }}</a></p>
        	<p>{% translate 'Price'%}: {{ product.price }}</p>
                {% translate 'no discount' as no_discount %}
        	<p>{% translate 'Discount' %}: {% firstof product.discount no_discount %}</p>
        	</div>
            {% if product.preview %}
                <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">            
            {% endif %}
            {% empty %}
                <div>{% translate 'No images' %}</div>
        {% endfor %}
    
    <div>
    {% if perms.shopapp %}
        {% if perms.shopapp.add_product %}
            <a href="{% url 'shopapp:create_product' %}">{% translate 'Create new product' %}</a>
        {% endif %}
    {% else %}
        <p>{% translate "You don't have permission to create new product" %}.</p>
    {% endif %}
    </div>
        
    {% else %}
        {% url 'shopapp:create_product' as create_product_url %}
        {% blocktranslate %}
        <h3>'No products yet' </h3>
            <a href="{{ create_product_url }}">'Create new one'</a>
        {% endblocktranslate %}
    {% endif %}


{% endblock %}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}
{% load cache %}
{% block title %}
    Shopp Index
{% endblock %}


{% block body %}
    <h1>Hello Shop Index</h1>

    <div>
        <ul>
            {% for name,price in products %}
                <li>{{ name|center:"15" }} for ${{ price }}</li>
                {% if name|length_is:'7'  %}
                <span>Lucky product</span>
                {% endif %}
            {% empty %}
                No products here
            {% endfor %}

        </ul>
    </div>
    
    <div>
        <strong>
            You have {{ items }} item{{ items|pluralize:"es" }}
        </strong>
    </div>
    
    <div>
    {% comment "Optional note" %}
    <p>Commented out text with {{ Now|date:"c" }}</p>
    {% endcomment %}
    </div>
    {% cache 100 lorem %}
    <div>
        {% lorem 3 p random %}
    </div>
    {% endcache %}
    <div>{{ Now|date:"M" }}</div>
    <div>
        Time running : {{ time_running }}
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/user_order_list.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title %}
    User orders
{% endblock %}

{% block body %}
    <div>
    <h1>User info</h1>
        {% if user_.profile %}
            {% if user_.profile.avatar %}
                <img src="{{ user_.profile.avatar.url }}" alt="{{ user_.profile.avatar.name }}">
                {% if user.username == user_.username or user.is_staff %}
                    <div>
                        <a href="{% url 'myauth:change-avatar' pk=user_.profile.pk %}">Change avatar</a>
                    </div>
                {% endif %}
            {% else %}
                <p>User don't have avatar</p>
                {% if user.username == user_.username or user.is_staff %}
                    <div>
                        <a href="{% url 'myauth:change-avatar' pk=user_.profile.pk %}">Set avatar</a>
                    </div>
                {% endif %}
            {% endif %}
        {% else %}
            <p>User don't have profile</p>
            {% if user.username == user_.username or user.is_staff %}
                <div>
                    <a href="{% url 'myauth:create-profile' pk=user.pk %}">Update profile</a>
                </div>
            {% endif %}
        {% endif %}


        <h2>Detail </h2>
        <p>Username: {{ user.username }}</p>
        <p>First name: {{ user.first_name }}</p>
        <p>Last name: {{ user.last_name }}</p>
        <p>Email: {{ user.email }}</p>
        <p>Bio: {{ user.profile.bio }}</p>
    </div>
    <div>
    <h1> Orders: </h1>
    {% if object_list %}
        {% cache 100 orderinfo  user.pk %}
        {% for order in object_list %}
            <div>
            <p><a href="{% url 'shopapp:order_details' pk=order.pk %}"> Deteils#{{ order.pk }}</a> </p>
        	<p>Order by: {% firstof order.user.first_name order.user.username %}</p>
        	<p>Promocode: {{ order.promocode }}</p>
        	<p>Delivery address: {{order.delivery_address}}</p>
            <div>
                Products in order:
                <ul>
                    {% for product in order.products.all %}
                        <li>{{ product.name }} for ${{ product.price }}</li>
                    {% endfor %}

                </ul>
            </div>
        	</div>
        {% endfor %}
        {% endcache %}
    {% else %}
        <h3> No Orders yet</h3>
    {% endif %}
    </div>
    <div>
        <a href="{% url 'shopapp:create_order' %}">Create new order</a>
    </div>
{% endblock %}