mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import logout_view, MyLogoutView, set_cookie_view, get_cookie_view, set_session_view, get_session_view, \
    AboutMeView, RegisterView, FooBarView, AvatarUpdateView, ProfileCreateView, UserListView, UserDetailView, HelloView

app_name = 'myauth'
urlpatterns = [
    # path('login/', login_view, name='login'),
    path('login/',
         LoginView.as_view(
             template_name='myauth/login.html',
             redirect_authenticated_user=True,
         ),
         name='login'),

    path('hello/', HelloView.as_view(), name='hello'),
    path('logout/', logout_view, name='logout'),

    path('about-me/', AboutMeView.as_view(), name='about_me'),
    path('register/', RegisterView.as_view(), name='register'),

    path('cookie/get', get_cookie_view, name='cookie_get'),
    path('cookie/set', set_cookie_view, name='cookie_set'),

    path('session/get', get_session_view, name='session_get'),
    path('session/set', set_session_view, name='session_set'),


    path('foo-bar/', FooBarView.as_view(), name='foo-bar'),
    path('user-list/', UserListView.as_view(), name='user-list'),
    path("user-details/<int:pk>", UserDetailView.as_view(), name="user-details"),
    path("user-details/<int:pk>/update-profile/", ProfileCreateView.as_view(), name="create-profile"),

    path("user-details/<int:pk>/avatar/", AvatarUpdateView.as_view(), name="change-avatar"),


]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from django.contrib.sitemaps.views import sitemap

from .sitemaps import sitemaps


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api/schema/swager/', SpectacularSwaggerView.as_view(url_name='schema'), name='swager'),
    path('api/', include('myapiapp.urls')),
    path('blog/', include('blogapp.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
]

urlpatterns += i18n_patterns(
    path('accounts/', include('myauth.urls')),
    path('shop/', include('shopapp.urls')),
    path('req/', include('requestdataapp.urls')),
    path('admin/', admin.site.urls),
)

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

mysite/myauth/models.py
from django.contrib.auth.models import User
from django.db import models

def profile_avatar_directory_path(instance: "Profile", filename: str) -> str:
    return f"Profile/profile_{instance.pk}/avatar/{filename}"

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    avatar = models.ImageField(upload_to=profile_avatar_directory_path, null=True, blank=True)

mysite/myauth/forms.py
from django import forms
from django.core import validators
from .models import Profile
from django.contrib.auth.models import Group, User


class UserAvatarForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = "avatar",

class UserProfileForm(forms.ModelForm):
    bio = forms.CharField(widget=forms.Textarea)
    agreement_accepted = forms.BooleanField(required=False)
    avatar = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = ("first_name", "last_name", "email")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.save()
        Profile.objects.create(user=user, bio=self.cleaned_data['bio'],
                               agreement_accepted=self.cleaned_data['agreement_accepted'],
                               avatar=self.cleaned_data['avatar'])
        return user

mysite/myauth/views.py
from random import random

from django import forms
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.models import User
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse, reverse_lazy
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView, CreateView, UpdateView, ListView, DetailView
from .models import Profile
from django.views import View
from .forms import UserAvatarForm, UserProfileForm
from django.utils.translation import gettext_lazy as _, ngettext_lazy
from django.views.decorators.cache import cache_page

class HelloView(View):
    welcome_message = _('Hello World!')
    def get(self, request: HttpRequest) -> HttpResponse:
        items_string = request.GET.get('items') or 0
        items = int(items_string)
        products_line = ngettext_lazy(
            "one product",
            "{count} products",
            items,
        )
        products_line = products_line.format(count=items_string)
        return HttpResponse(
            f'<h1>{self.welcome_message}</h1>'
            f'\n<h2>{products_line}</h1>'
                            )


def login_view(request: HttpRequest) -> HttpResponse:
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('/admin')
        return render(request, 'myauth/login.html')

    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect('/admin')

    return render(request, 'myauth/login.html', {'error': 'Invalid username or password.'})


class MyLogoutView(LogoutView):
    next_page = reverse_lazy('myauth:login')


def logout_view(request: HttpRequest) -> HttpResponse:
    logout(request)
    return redirect(reverse("myauth:login"))

@user_passes_test(lambda u: u.is_superuser)
def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse("Cookie set")
    response.set_cookie("fizz", "buzz", max_age=3600)
    return response

@cache_page(60*2)
def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get("fizz", "Default value")
    return HttpResponse(f'Cookie value: {value!r} + {random()}')


@permission_required("myauth.view_profile", raise_exception=True)
def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session["foobar"] = "spamegs"
    return HttpResponse('Session set')


@login_required
def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get("foobar", "Default value")
    return HttpResponse(f'Session value: {value!r}')

class ProfileCreateView(UserPassesTestMixin, UpdateView):
    def test_func(self):
        self.object = self.get_object()
        if self.request.user.is_staff:
            return True
        user_is_current_user = str(self.object.username) == str(self.request.user)
        return user_is_current_user
    model = User
    form_class = UserProfileForm
    template_name = 'myauth/user_profile_form.html'
    def get_success_url(self):
        return reverse(
            "myauth:about_me",
        )

class AvatarUpdateView(UserPassesTestMixin, UpdateView):
    def test_func(self):
        self.object = self.get_object()
        if self.request.user.is_staff:
            return True
        user_is_current_user = str(self.object.user.username) == str(self.request.user)
        return user_is_current_user

    model = Profile
    form_class = UserAvatarForm
    template_name = 'myauth/user_avatar_form.html'
    def get_success_url(self):
        return reverse(
            "myauth:about_me",
        )


class AboutMeView(TemplateView):
    queryset = User.objects.prefetch_related('profile')
    context_object_name = 'user_'
    template_name = 'myauth/about-me.html'


class UserDetailView(DetailView):
    queryset = User.objects.prefetch_related('profile')
    context_object_name = 'user_'
    template_name = 'myauth/about-me.html'



class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    bio = forms.CharField(widget=forms.Textarea)
    agreement_accepted = forms.BooleanField(required=False)

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "password1", "password2")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.save()
        Profile.objects.create(user=user, bio=self.cleaned_data['bio'],
                               agreement_accepted=self.cleaned_data['agreement_accepted'])
        return user






class RegisterView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'myauth/register.html'
    success_url = reverse_lazy('myauth:about_me')

    def form_valid(self, form):
        response = super().form_valid(form)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(self.request,
                            username=username,
                            password=password)
        login(self.request, user)
        return response

class FooBarView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        return JsonResponse({'foo': 'bar', 'bar': 'baz'})


class UserListView(ListView):
    template_name = 'myauth/user_list.html'
    model = User
    context_object_name = 'users'

mysite/myauth/templates/myauth/about-me.html
{% extends 'myauth/base.html' %}

{% block title %}
    About me
{% endblock %}

{% block body %}
    <h1>User info</h1>
    {% if user.is_authenticated %}

            {% if user_.profile %}
                {% if user_.profile.avatar %}
                    <img src="{{ user_.profile.avatar.url }}" alt="{{ user_.profile.avatar.name }}">
                    {% if user.username == user_.username or user.is_staff %}
                        <div>
                            <a href="{% url 'myauth:change-avatar' pk=user_.profile.pk %}">Change avatar</a>
                        </div>
                    {% endif %}
                {% else %}
                    <p>User don't have avatar</p>
                    {% if user.username == user_.username or user.is_staff %}
                        <div>
                            <a href="{% url 'myauth:change-avatar' pk=user_.profile.pk %}">Set avatar</a>
                        </div>
                    {% endif %}
                {% endif %}
            {% else %}
                <p>User don't have profile</p>
                {% if user.username == user_.username or user.is_staff %}
                    <div>
                        <a href="{% url 'myauth:create-profile' pk=user.pk %}">Update profile</a>
                    </div>
                {% endif %}
            {% endif %}


        <h2>Detail</h2>
        <p>Username: {{ user.username }}</p>
        <p>First name: {{ user.first_name }}</p>
        <p>Last name: {{ user.last_name }}</p>
        <p>Email: {{ user.email }}</p>
        <p>Bio: {{ user.profile.bio }}</p>

    {% else %}
        <h2> User is anonymous</h2>
    {% endif %}
{% endblock %}

mysite/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base Title
        {% endblock %}
    </title>
</head>
<body>
{% block body %}
    Base body
{% endblock %}
<div>
    {% now 'H:i' %}
</div>
<div>
    {% now 'l' as current_weekday %}
    Today is {{ current_weekday }}
</div>
</body>
</html>

mysite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}
       {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
{% endblock %}

mysite/myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}

{% block title %}
	Register
{% endblock %}

{% block body %}
	<h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
{% endblock %}

mysite/myauth/templates/myauth/user_avatar_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Set avatar
{% endblock %}

{% block body %}
    <h1>Update avatar</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form.as_p }}

            <button type="submit">Submit</button>
        </form>
    </div>

    <div>
        <a href="{% url 'myauth:about_me' %}">Back to profil</a>
    </div>
{% endblock %}

mysite/myauth/templates/myauth/user_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Users list
{% endblock %}

{% block body %}
    <h1> Users: </h1>
    {% if users %}
        <ul>
        {% for user in users %}

            <li>
{#               {% firstof user.first_name user.username %}#}
                <p><a href="{% url 'myauth:user-details'  pk=user.pk %}" >Username: {{ user.username }}</a></p>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <h3> No users yet</h3>
    {% endif %}
    
{% endblock %}

mysite/myauth/templates/myauth/user_profile_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Update profile
{% endblock %}

{% block body %}
    <h1>Update user profile</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form.as_p }}

            <button type="submit">Submit</button>
        </form>
    </div>

    <div>
        <a href="{% url 'myauth:about_me' %}">Back to profile</a>
    </div>
{% endblock %}